---
build:
  environment:
    php:
      version: "7.4.3"
  cache:
    disabled: false
    directories:
      - ~/.composer/cache
  nodes:
    tests:
      commands:
    diving:
      tests:
        override:
          - php-scrutinizer-run --sub-project-dir=application/src
          - vendor/bin/phpspec run
    app:
      tests:
        override:
          - php-scrutinizer-run --sub-project-dir=application/app
          - vendor/bin/phpunit --prepend "./tests/unit/xdebug-filter.php"
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
