build:
    nodes:
        diving:
            environment:
                php:
                  version: 7.4
            cache:
                disabled: false
                directories:
                    - ~/.composer/cache
