---
language: php
php:
  - 7.4.1
cache:
  directories:
    - $HOME/.composer/cache
jobs:
  fast_finish: true

script:
  - php vendor/bin/phplint
  - php vendor/bin/phpspec run
  - php vendor/bin/phpunit --prepend "./tests/unit/xdebug-filter.php"
  - php vendor/bin/infection --debug -j2 --filter=application/app --coverage=build/coverage/phpunit/ --test-framework=phpunit
  - php vendor/bin/phpcs --runtime-set ignore_warnings_on_exit true --cache -p application tests

