language: php
php:
- 7.4.3
cache:
  directories:
  - "$HOME/.composer/cache"
jobs:
  fast_finish: true
before_script:
- composer install
script:
- php vendor/bin/phplint
- php vendor/bin/phpspec run
- php vendor/bin/phpunit --prepend "./tests/unit/xdebug-filter.php"
- php vendor/bin/infection --debug -j2 --filter=application/app --coverage=build/coverage/phpunit/
  --min-covered-msi=94 --min-msi=94 --test-framework=phpunit
- php vendor/bin/phpcs --runtime-set ignore_warnings_on_exit true --cache -p application
  tests
after_success:
- travis_retry bash <(curl -s https://codecov.io/bash)
- travis_retry php vendor/bin/php-coveralls
env:
  global:
    - secure: ZDPWiprlCII1swFbT8ZUSO+gPHvBQYoEl8FrPJ4hM/4GKNc4ev7cMjWNa4HNNBwsIpEJGBiJWB45j5WrCuZbArekKlIY3ZoSyMY4/P9klO8LhFBoVSQDKkDzoRb3yRxA54bPc/0o+ZpOIX6DRlLy9xOgKOGDVnkLNHW10j3YHfdKlafe0Ou1Peo2SA0hkvPdUDnXowJEZDtmrx/QZLb8uROTJN/PWx72mDHbNyuzb1KnTs2WBd6cBZXHiXKfe9y3hPtbRPhkjH/KAv/wpWLuWXB16sGaJzHUdqoIa4rnNqKv8lJI672DnGVQBO8CJWotk2YxfkEZHQAxGdCa6DJ5EhwokZFrYdbtiTUzrBbJGZXaFNtkWKmMgbMxFYVAfHEjUgvmmzlvjkySZJlmr7Mlue7PNIeUc4WFWEMKLl+/RaaHHXkmR76YJKtO06rcBU+NOfFKIEgQywMrrvXZLYmcqhh31jzB0v2GEgNoq+WXirY8Mg0eSTBVECMeV7IkbcpXx6tJmRP8fWV0qyP6S2k/xdheTAHIbJp7d4V9Kf+/jZkmEpc1yvjxQtHd/CZuYqSaxw0un5OZZkgjRFCoZKk6BFCmkzbzol+6i0hIEvr88OutoWUlrJh+Jnig1uPYfA/vuM7zlvpGelpCzadh+L127xVpVjY0i0gq+jTY/x8D44s=
    - secure: YiKwn4vZwy8O0PBt5+RnXyzE18r6+KE4Sv44icNOtNQpzKAvrgAa+ra6MLQlVlfFBrxr3geHmU/wWmy/hJI3IW/0AyLpMoQfw4e9qgOTRBeVDeRg+lMFcp8kLbn9k5zGh4ZTjBOahVn941WN6zKj+h2TIs/Mhgl7mEYMdZBBaQL4iRTS+6HiZvCLcSKL2fOlu0C1xozV0zsueCeUNguV6pDdsUjQFPA+qgp1UYUe4bdbh44R620fWTn0KkCjNhVc+A9dXXzk/gOSn4nJ3V43eytaJgKUzcB9TSsqdEVLDVE39BYz6ybMGpkNW6SYDDqoMiTzAsB8NuAJzA5W1V1N7w7iCA4BTssHnH2vZ5kN9Mk+13eogzALTx1ofseIfDzlPVPxlBiRIebw0zWISTuS0eqmdm89X7NRasbAxzYmE0HEQJl0U2oFOHfEkFtsXRKCY4S1ZRxL6tZLFTWWgaiqnHVjIrE8P5JYFNKe5YQ78fXcA5iJ/WWSenkaGglfdPyOABvGSZ1qBGjophBtE40E1gMMpJUw6eeWGZAnA75wdxqpm1g0KBhx6nxJt/rnuT0BAAER0wPSK+A1mdXUaYnstd9nUBgBUKsT1aOrAIHr68oP0SavY3i/jMBHEPV4RSpYDY0nj1lLeQZx+yS2Ns/MmcIJ8hVytPBht4dA+iZroqw=
