---
language: php
php:
  - 7.4.3
cache:
  directories:
  - "$HOME/.composer/cache"
jobs:
  fast_finish: true
before_script:
  - composer install
script:
  - php vendor/bin/phplint
  - php vendor/bin/phpspec run
  - php vendor/bin/phpunit --prepend "./tests/unit/xdebug-filter.php"
  - php vendor/bin/infection --debug -j2 --filter=application/app --coverage=build/coverage/phpunit/ --min-covered-msi=${MIN_COVERED_MSI:-95} --min-msi=${MIN_MSI:-94} --test-framework=phpunit
  - php vendor/bin/phpcs --runtime-set ignore_warnings_on_exit true --cache -p application tests
after_success:
  - travis_retry bash <(curl -s https://codecov.io/bash) -s build/coverage/phpunit -s build/coverage/phpspec/phpspec-coverage-xml
  - travis_retry php vendor/bin/php-coveralls
env:
  global:
    - secure: Xzjs1hgUsef/sOKXNhbb7oq4xQAj+TOgl95uE+KjBXvj9VZ71bpFR6j/wOsbFtb71Imj3i1LQnPy5RXigvcRd2uFMnn4ybI+PRygjZr4mRmBg3W0r1P0DNvEjw9f/xbiBg2v4ivdtZYL58zUa75jOMvfAb3OGPclYggdy+GVN5E+tytLni6xZR4HJFILKY8t1ayMJ0ZQk0JQXO0Jh/GS3fvN7p5QCu26PLsp6YZytGE5HILKiOrNcCzri/ebmK4pJMkzZRP93ywf8755+C3HJscyUAHF4IR8W9oq5VbbBGqfH0/52IxmjNxly8t2IZAYMTUB6NKMpFf/kYW2q7rhY8BluFBTegJQsc8s1SILfEwgx6BitMG/o9FI++b2s44VqKPVNrLY2gDPAwXqCSUD4zfv3xPSVCl5r/q9FxrEh7QqtlYZEQdyGasJVPbF/mBOOi4NirtiRBI1rCG+OEwGbhv2oycJ7OMbKy8sVEKz4iDdsbthytMRt+X8VXmRL8G5IhJt2llKqbLSGebds0YsW4vZLwOWNns4OykXiUXBT8aXodJ2IObTPSwd8bKPwFYQiAik60SSJOZnJGwe8XKs752BQGUZdcCABJzIwrzgtZ6UXwg6VVnbjeDMnUg5gSs2O1WE/r74oTNYpfultWKt4y6jUouzBHaUtWh7V5UK388=
    - secure: uBAHE9bSgIPnA7OIbrq5Nzhf74KFwf9YsXpuX3S6QwFgFou/TkwuaH0mqte+l4dWIvFDAVqtqZdwNs0I3kMzgjPcYqwdoFTWQe3EONxk2WY9/UEjEk0JEZ70WR/r1xn0SaH3ieRulpxqIq7weq5DscU52ZmerucfWFeAs1XXMvucSGMnWiDZ6r60Vwc8SiaPAdpnQoHQVpIqRCEN86Y/01WvMCf9x+5Pf9Oh5+aPyu7qRixq2YKTXihFjvdKtEGL1OAcyCtCp2C5yUqw13yVUfHtde+Ic3Y3UQLpHCWG/JyEJMFMyn1rHyIF3d7jMN7ApTqwLrlVYKNnbnZKi60U12yg56HMfQVC74tQnJFA/Ky7UZXv4+FKBiv49j8xs7XVnzX01PY9YYN1lgbckSvOPlsq5mxsKBCQCUY5gy+HmdgC6zJaT803rS/V058CoVbhFRyYS4B9yNOyY21W5DTvMnFb7it84R9dz/l+RxfqNOKEfHlWOzUEUiPRH11Hn3J6TJuhu4lA1AZiDwXaEMA03B5kbiPga6sR2l4W7BTlTEeIW/19bbGFbrhhDCmgkSdfVNc1VlmYVjVlYpiYspF9WTu3sEFBIEgMLXO9wnL40IurIw9pN6onNw4AHN9jXY0R1RN5q80v2HLoIzf6wZrcYcVqBsq20PAGy5+kPpVSxhE=
