"use strict";
const path = require("path");
const FaviconsWebpackPlugin = require("favicons-webpack-plugin");

module.exports = (baseDir) => {
  return new FaviconsWebpackPlugin({
    // Your source logo (required)
    logo: path.resolve(baseDir, "public/img/icon.png"),
    // Enable caching and optionally specify the path to store cached data
    // Note: disabling caching may increase build times considerably
    cache: true,
    // Override the publicPath option usually read from webpack configuration
    //publicPath: "/fav",
    // The directory to output the assets relative to the webpack output dir.
    // Relative string paths are allowed here ie "../public/static". If this
    // option is not set, `prefix` is used.
    //outputPath: "/fav",
    // Prefix path for generated assets
    prefix: "fav/",
    // Inject html links/metadata (requires html-webpack-plugin).
    // This option accepts arguments of different types:
    //  * boolean
    //    `false`: disables injection
    //    `true`: enables injection if that is not disabled in html-webpack-plugin
    //  * function
    //    any predicate that takes an instance of html-webpack-plugin and returns either
    //    `true` or `false` to control the injection of html metadata for the html files
    //    generated by this instance.
    inject: true
  });
};
