---
parameters:
  env(KIT_REPO_ITEM_API_VERSION): '1.1'
  env(KIT_REPO_ITEM_API_HOSTNAME): https://google.co.uk

  app.kit.repository.item.oauth.access_token: '%env(string:KIT_REPO_ITEM_API_OAUTH_TOKEN)%'
  app.kit.repository.item.oauth.token_secret: '%env(string:KIT_REPO_ITEM_API_OAUTH_SECRET)%'
  app.kit.repository.item.consumer_key: '%env(string:KIT_REPO_ITEM_API_CONSUMER_KEY)%'
  app.kit.repository.item.consumer_secret: '%env(string:KIT_REPO_ITEM_API_CONSUMER_SECRET)%'

  app.kit.repository.item.api.version: 'env(string:KIT_REPO_ITEM_API_VERSION)%'
  app.kit.repository.item.api.host_name: '%env(string:KIT_REPO_ITEM_API_HOSTNAME)%'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\Kit\:
    resource: '%kernel.project_dir%/app/Kit/*'
    exclude: '%kernel.project_dir%/app/Kit/{DependencyInjection}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Kit\Controller\:
    resource: '%kernel.project_dir%/app/Kit/Controller'
    tags: ['controller.service_arguments']

  App\Kit\Query\Bus\ItemDetailQueryBusInterface: '@App\Kit\Query\Bus\SymfonyQueryBus'

  App\Kit\Repository\Item\ItemRepositoryInterface: '@App\Kit\Repository\Item\ItemApi'

  App\Kit\Repository\Manufacturer\ManufacturerApi:
    arguments:
      - '@app.kit.repository.manufacturer.client'

  App\Kit\Repository\Item\ItemApi:
    arguments:
      - '@app.kit.repository.client.psr18'

  App\Kit\Repository\Item\Decorator\Cache:
    decorates: App\Kit\Repository\Item\ItemRepositoryInterface
    arguments:
      - '@App\Kit\Repository\Item\Decorator\Cache.inner'
      - '@app.kit.repository.item.decorator.cache'

  app.kit.repository.item.decorator.cache:
    class: Symfony\Component\Cache\Psr16Cache
    arguments:
      - '@kit.item.cache'

  app.kit.repository.client.curl:
    class: Symfony\Component\HttpClient\CurlHttpClient

  Nyholm\Psr7\Factory\Psr17Factory: ~

  Psr\Http\Message\ResponseFactoryInterface: '@Nyholm\Psr7\Factory\Psr17Factory'
  Psr\Http\Message\StreamFactoryInterface: '@Nyholm\Psr7\Factory\Psr17Factory'

  app.kit.repository.client.psr18:
    class: Symfony\Component\HttpClient\Psr18Client
    arguments:
      - '@app.kit.repository.client.curl'
      - '@Psr\Http\Message\ResponseFactoryInterface'
      - '@Psr\Http\Message\StreamFactoryInterface'

  Shrikeh\Diving\Kit\:
    resource: '%kernel.project_dir%/src/Kit/*'
