---
parameters:
  env(KIT_REPO_ITEM_API_VERSION): '1.1'
  env(KIT_REPO_ITEM_API_HOSTNAME): https://google.co.uk

  app.kit.repository.item.oauth.access_token: '%env(string:KIT_REPO_ITEM_API_OAUTH_TOKEN)%'
  app.kit.repository.item.oauth.token_secret: '%env(string:KIT_REPO_ITEM_API_OAUTH_SECRET)%'
  app.kit.repository.item.consumer_key: '%env(string:KIT_REPO_ITEM_API_CONSUMER_KEY)%'
  app.kit.repository.item.consumer_secret: '%env(string:KIT_REPO_ITEM_API_CONSUMER_SECRET)%'

  app.kit.repository.item.api.version: 'env(string:KIT_REPO_ITEM_API_VERSION)%'
  app.kit.repository.item.api.host_name: '%env(string:KIT_REPO_ITEM_API_HOSTNAME)%'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\Kit\:
    resource: '%kernel.project_dir%/app/Kit/*'
    exclude: '%kernel.project_dir%/app/Kit/{DependencyInjection}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Kit\Controller\:
    resource: '%kernel.project_dir%/app/Kit/Controller'
    tags: ['controller.service_arguments']

  App\Kit\Query\Bus\ItemDetailQueryBusInterface: '@App\Kit\Query\Bus\SymfonyQueryBus'

  App\Kit\Repository\Item\ItemRepositoryInterface: '@App\Kit\Repository\Item\ItemApi'

  App\Kit\Repository\Manufacturer\ManufacturerApi:
    arguments:
      - '@app.kit.repository.manufacturer.client'

  App\Kit\Repository\Item\ItemApi:
    arguments:
      - '@app.kit.repository.item.client'

  App\Kit\Repository\Item\Decorator\Cache:
    decorates: App\Kit\Repository\Item\ItemRepositoryInterface
    arguments:
      - '@App\Kit\Repository\Item\Decorator\Cache.inner'
      - '@app.kit.repository.item.decorator.cache'

  app.kit.repository.item.decorator.cache:
    class: Symfony\Component\Cache\Psr16Cache
    arguments:
      - '@kit.item.cache'

  app.kit.repository.item.client.handler_stack:
    class: GuzzleHttp\HandlerStack
    factory: [GuzzleHttp\HandlerStack, create]
    arguments:
      - '@GuzzleHttp\Handler\CurlMultiHandler'
    calls:
      - method: push
        arguments:
          - '@app.kit.repository.item.client.oauth'

  app.kit.repository.item.client.oauth:
    class: GuzzleHttp\Subscriber\Oauth\Oauth1
    arguments:
      - consumer_key: '%app.kit.repository.item.consumer_key%'
        consumer_secret: '%app.kit.repository.item.consumer_secret%'
        token: '%app.kit.repository.item.oauth.access_token%'
        token_secret: '%app.kit.repository.item.oauth.token_secret%'

  GuzzleHttp\Handler\CurlMultiHandler: ~

  app.kit.repository.item.client:
    class: GuzzleHttp\Client
    arguments:
      -  timeout: '5.0'
         base_uri: '%app.kit.repository.item.api.host_name%/%app.kit.repository.item.api.version%/'
         handler: '@app.kit.repository.item.client.handler_stack'
         auth: oauth

  app.kit.repository.manufacturer.client:
    class: GuzzleHttp\Client

  Shrikeh\Diving\Kit\:
    resource: '%kernel.project_dir%/src/Kit/*'
