---
parameters:
  env(KIT_ITEM_API_VERSION): '1.1'
  env(KIT_ITEM_API_HOSTNAME): https://google.co.uk

  env(KIT_MANUFACTURER_API_HOSTNAME): https://google.co.uk
  env(KIT_MANUFACTURER_API_VERSION): '1.1'

  app.kit.repository.item.oauth.access_token: '%env(string:KIT_REPO_ITEM_API_OAUTH_TOKEN)%'
  app.kit.repository.item.oauth.token_secret: '%env(string:KIT_REPO_ITEM_API_OAUTH_SECRET)%'
  app.kit.repository.item.consumer_key: '%env(string:KIT_ITEM_API_CONSUMER_KEY)%'
  app.kit.repository.item.consumer_secret: '%env(string:KIT_ITEM_API_CONSUMER_SECRET)%'

  app.kit.repository.item.api.version: 'env(string:KIT_ITEM_API_VERSION)%'
  app.kit.repository.item.api.host_name: '%env(string:KIT_ITEM_API_HOSTNAME)%'

  app.kit.repository.manufacturer.api.version: 'env(string:KIT_MANUFACTURER_API_VERSION)%'
  app.kit.repository.manufacturer.api.host_name: '%env(string:KIT_MANUFACTURER_API_HOSTNAME)%'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\Kit\:
    resource: '%kernel.project_dir%/app/Kit/*'
    exclude: '%kernel.project_dir%/app/Kit/{DependencyInjection}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Kit\Controller\:
    resource: '%kernel.project_dir%/app/Kit/Controller'
    tags: ['controller.service_arguments']

  App\Kit\Query\Bus\ItemDetailQueryBusInterface: '@App\Kit\Query\Bus\SymfonyQueryBus'

  Nyholm\Psr7\Factory\Psr17Factory: ~

  Psr\Http\Message\ResponseFactoryInterface: '@Nyholm\Psr7\Factory\Psr17Factory'
  Psr\Http\Message\StreamFactoryInterface: '@Nyholm\Psr7\Factory\Psr17Factory'

# Item Repository

  App\Kit\Repository\Item\ItemRepositoryInterface: '@App\Kit\Repository\Item\ItemApi'
  App\Kit\Repository\Item\ModelFactory\Psr7ResponseItemModel:
    arguments:
      - '@app.kit.repository.item.response_parser'

  App\Kit\Repository\Item\ItemApi:
    arguments:
      - '@app.kit.repository.item.client.psr18'
      - '@app.kit.repository.item.request_factory'
      - '@App\Kit\Repository\Item\ModelFactory\ItemModelFactoryInterface'

  App\Kit\Repository\Item\Decorator\Cache:
    decorates: App\Kit\Repository\Item\ItemRepositoryInterface
    arguments:
      - '@App\Kit\Repository\Item\Decorator\Cache.inner'
      - '@app.kit.repository.item.decorator.cache'

  app.kit.repository.item.decorator.cache:
    class: Symfony\Component\Cache\Psr16Cache
    arguments:
      - '@kit.item.cache'

  app.kit.repository.item.client.curl:
    class: Symfony\Component\HttpClient\CurlHttpClient
    arguments:
      - base_uri: '%app.kit.repository.item.api.host_name%'

  app.kit.repository.item.client.psr18:
    class: Symfony\Component\HttpClient\Psr18Client
    arguments:
      - '@app.kit.repository.item.client.curl'
      - '@Psr\Http\Message\ResponseFactoryInterface'
      - '@Psr\Http\Message\StreamFactoryInterface'

  app.kit.repository.item.api.base_request:
    class: Nyholm\Psr7\Request
    arguments:
      - GET
      - '%app.kit.repository.item.api.host_name'

  app.kit.repository.item.api.base_uri:
    class: GuzzleHttp\Psr7\Uri
    arguments:
      - '/'

  app.kit.repository.item.request_factory:
    class: App\Kit\Repository\RequestFactory\GuzzleRequestFactory
    arguments:
      - '@app.kit.repository.item.api.base_request'
      - '@app.kit.repository.item.api.base_uri'

  app.kit.repository.item.response_parser:
    class: App\Kit\ResponseParser\ItemDetail

# Manufacturer Repository

  App\Kit\Repository\Manufacturer\ManufacturerRepositoryInterface: '@App\Kit\Repository\Manufacturer\ManufacturerApi'
  App\Kit\Repository\Manufacturer\ModelFactory\Psr7ResponseManufacturerModel:
    arguments:
      - '@app.kit.repository.manufacturer.response_parser'

  App\Kit\Repository\Manufacturer\ManufacturerApi:
    arguments:
      - '@app.kit.repository.manufacturer.client.psr18'
      - '@app.kit.repository.manufacturer.request_factory'
      - '@App\Kit\Repository\Manufacturer\ModelFactory\ManufacturerModelFactoryInterface'

  app.kit.repository.manufacturer.client.psr18:
    class: Symfony\Component\HttpClient\Psr18Client
    arguments:
      - '@app.kit.repository.manufacturer.client.curl'
      - '@Psr\Http\Message\ResponseFactoryInterface'
      - '@Psr\Http\Message\StreamFactoryInterface'

  app.kit.repository.manufacturer.client.curl:
    class: Symfony\Component\HttpClient\CurlHttpClient
    arguments:
      - base_uri: '%app.kit.repository.manufacturer.api.host_name%'

  app.kit.repository.manufacturer.api.base_request:
    class: Nyholm\Psr7\Request
    arguments:
      - GET
      - '%app.kit.repository.manufacturer.api.host_name'

  app.kit.repository.manufacturer.api.base_uri:
    class: GuzzleHttp\Psr7\Uri
    arguments:
      - '/'

  app.kit.repository.manufacturer.request_factory:
    class: App\Kit\Repository\RequestFactory\GuzzleRequestFactory
    arguments:
      - '@app.kit.repository.manufacturer.api.base_request'
      - '@app.kit.repository.manufacturer.api.base_uri'

  app.kit.repository.manufacturer.response_parser:
    class: App\Kit\ResponseParser\ItemDetail

  Shrikeh\Diving\Kit\:
    resource: '%kernel.project_dir%/src/Kit/*'
