---
qualifications:
  padi_open_water:
    title: PADI Advanced Open Water Diver
    agency: PADI
    completed: 2014-01-01
    location: Negril, Jamaica

  bsac_ocean_diver:
    title: BSAC Ocean Diver
    agency: British Sub Aqua Club
    completed: 2014-01-01
    location: Kao Tao, Thailand
