.ONESHELL:
SHELL := /usr/bin/env sh
.DEFAULT: help
.PHONY: help
ifndef VERBOSE
.SILENT:
endif

test: test-php

test-php: composer-validate phplint infection behat phpcs phpmd phpstan psalm phpmetrics codecept-integration

test-ci: phplint infection behat phpcs phpmd phpstan

lint-changed: lint-changed-php

lint-changed-php:
	echo "Linting changed PHP files..."
	 ${ROOT_DIR}/tools/bin/lint-changed-php.sh

validate: composer-validate lint

composer-validate:
	echo 'Validating composer...'
	composer validate

lint: eslint phplint

eslint:

phpunit:
	echo 'Running phpunit...'
	php ./vendor/bin/phpunit --prepend "./tests/unit/xdebug-filter.php"

infection: phpunit phpspec infection-phpunit #infection-phpspec

infection-phpunit:
	echo 'Running infection against PHPUnit...'
	php ${ROOT_DIR}/vendor/bin/infection --debug -j2 --filter=$(ROOT_DIR)/application/app --coverage=$(ROOT_DIR)/build/coverage/phpunit/ --test-framework=phpunit

infection-phpspec:
	echo 'Running infection against phpspec...'
	phpdbg -qrr ${ROOT_DIR}/vendor/bin/infection --debug -j2 --filter=$(ROOT_DIR)/application/src --coverage=$(ROOT_DIR)/build/coverage/phpspec/ --test-framework=phpspec

behat:
	echo 'Running behat test suite...'
	php ${ROOT_DIR}/vendor/bin/behat

phplint:
	echo 'Running phplint...'
	php ${ROOT_DIR}/vendor/bin/phplint

phpstan:
	echo 'Running phpstan...'
	php -d memory-limit=128M ${ROOT_DIR}/vendor/bin/phpstan analyse

psalm:
	php ${ROOT_DIR}/vendor/bin/psalm --show-info=true

phan:
	php ${ROOT_DIR}/vendor/bin/phan --analyze-twice --allow-polyfill-parser --strict-type-checking --color --load-baseline=${ROOT_DIR}/.phan/baseline.php

phpcs:
	echo 'Running codesniffer...'
	php ${ROOT_DIR}/vendor/bin/phpcs --runtime-set ignore_warnings_on_exit true --cache -p application tests

phpcbf:
	php ${ROOT_DIR}/vendor/bin/phpcbf -p --runtime-set ignore_warnings_on_exit true

rector-safe:
	${ROOT_DIR}/vendor/bin/rector process ${ROOT_DIR}/application/src --config ${ROOT_DIR}/vendor/thecodingmachine/safe/rector-migrate-0.6.yml
	${ROOT_DIR}/vendor/bin/rector process ${ROOT_DIR}/application/app --config ${ROOT_DIR}/vendor/thecodingmachine/safe/rector-migrate-0.6.yml

phpspec:
	echo 'Running phpspec...'
	${ROOT_DIR}/vendor/bin/phpspec run

phpmetrics:
	echo 'Creating phpmetrics...'
	php -d memory-limit=256M ${ROOT_DIR}/vendor/bin/phpmetrics --junit="${ROOT_DIR}/build/coverage/phpunit/junit.xml" --report-html="${ROOT_DIR}/docs/metrics" \
	  --exclude="build","dist","tests","vendor","tools","public","translations","application/var","application/app/Kernel", "vendor" ${ROOT_DIR}

browse-metrics:
	open file:///${ROOT_DIR}/docs/metrics/index.html

phpmd:
	echo 'Running PHP Mess Detector...'
	phpdbg -qrr ${ROOT_DIR}/vendor/bin/phpmd application text phpmd.xml.dist --verbose

codecept-integration:
	php ${ROOT_DIR}/vendor/bin/codecept run integration;
